### ISSUE TITLE
Terminals start at /home/jovyan

### ISSUE THREAD

**Issue by maray** [ChileanVirtualObservatory/jovial.chivo.cl#10]
For a strange reason terminals start at /home/jovyan. This is at least strange.

**Comment by mosoriob** [comment]
Maybe, the problem is related to notebook envs 
```
docker inspect 319f48ad48b0  | grep NB_
                "NB_USER=jovyan",
                "NB_UID=1000",
                "NB_GID=100",
```

what do you think @madiazp?

**Comment by madiazp** [comment]
The DockerFile should delete jovyan and it files, i'll check that.

**Comment by madiazp** [comment]
jovyan disappeared but the first directory in the terminal is /home and not home/$user even though is literally in the script
`notebook_arg="--notebook-dir=$(/home/$USER)" `
but I think that at the momment this is not an important issue.  In the terminal you appear in /home and in jovial kernel like /home/$user
