### ISSUE TITLE
Mirror conda

### ISSUE THREAD

**Issue by mosoriob** [ChileanVirtualObservatory/jovial.chivo.cl#3]
If we want to improve the download speed

**Comment by maray** [comment]
I think is a great idea. To who we should assign this task @madiazp ?

**Comment by capgadsx** [comment]
After some investigation this is not possible due to legal restrictions:

(from [https://repo.continuum.io/pkgs/](https://repo.continuum.io/pkgs/)):

> Anaconda and Miniconda are trademarks of Anaconda, Inc. Public mirrors of this are not allowed without express permission from Anaconda, Inc. For private mirrors and technical support, we encourage you to look at Anaconda Enterprise and Anaconda Support.
