### ISSUE TITLE
Installed packages

### ISSUE THREAD

**Issue by mosoriob** [ChileanVirtualObservatory/jovial.chivo.cl#6]
Check installed packages and modify docker image with packages needed.

**Comment by mosoriob** [comment]
Git isn't installed 👎

**Comment by mosoriob** [comment]
Installed:
- git
- gcc
- svn
- curl

**Comment by capgadsx** [comment]
With build-essential we should have everything

**Comment by mosoriob** [comment]
Added in the Dockerfile

**Comment by maray** [comment]
less, vim, conda, emacs...
